spring:
  application:
    name: api-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    preferIpAddress: true
server:
  port: 8050
zuul:
  retryable: true
