server:
  port: 8010
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    preferIpAddress: true
spring:
  application:
    name: consumer-ribbon
