server:
  port: 8011
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    preferIpAddress: true
spring:
  application:
    name: consumer-feign
feign:
  hystrix:
    enabled: true
hystrix:
  metrics:
    enabled: true
